### ISSUE TITLE
Error receiving response. Unable to read beyond the end of the stream

### ISSUE THREAD

**Issue by dojo90** [convertersystems/opc-ua-client#164]
I have a Siemens 15xx PLC with the following `struct`:

![grafik](https://user-images.githubusercontent.com/17551597/92579246-3fa04500-f28d-11ea-8fda-933cffb89b6b.png)

![grafik](https://user-images.githubusercontent.com/17551597/92581690-467c8700-f290-11ea-9736-ace45c94e8b0.png)

I made the following `Structure` class:

```csharp
[BinaryEncodingId("nsu=http://www.siemens.com/simatic-s7-opcua;s=TE_\"HTOPC_EquipmentModule_V1\"")]
internal class EquipmentModuleStructure : Structure
{
	public override void Decode(IDecoder decoder)
	{

	}

	public override void Encode(IEncoder encoder)
	{
		
	}
}
```

Everytime when I try to read the `node` I get one of the following errors and my `channel` breaks:

![grafik](https://user-images.githubusercontent.com/17551597/92582005-b428b300-f290-11ea-97f0-692c0f5b3a03.png)

I don't get any more logging output.
![grafik](https://user-images.githubusercontent.com/17551597/92583035-0918f900-f292-11ea-944c-1cb069351d0c.png)

> Error receiving response. Unable to read beyond the end of the stream.
> Error receiving response. Arithmetic operation resulted in an overflow.

Is there something wrong with my setup? The funny thing is that I can read out the status, for example. The error also occurs when I have no logic within the Decode() (see example above).

![grafik](https://user-images.githubusercontent.com/17551597/92582447-40d37100-f291-11ea-8470-e20cf65e3a22.png)

// Edit 1: Add exception

```txt
   at Workstation.ServiceModel.Ua.Channels.BinaryDecoder.ReadDiagnosticInfoArray(String fieldName)
   at Workstation.ServiceModel.Ua.ReadResponse.Decode(IDecoder decoder)
   at Workstation.ServiceModel.Ua.Channels.UaTcpSecureChannel.<ReceiveResponseAsync>d__132.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Workstation.ServiceModel.Ua.Channels.UaTcpSecureChannel.<ReceiveResponsesAsync>d__131.MoveNext()
```

![grafik](https://user-images.githubusercontent.com/17551597/92584288-c0623f80-f293-11ea-8514-ea1b1e5a565e.png)

// Edit 2: Added better Exception

```txt
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt32()
   at Workstation.ServiceModel.Ua.Channels.BinaryDecoder.ReadString(String fieldName)
   at Workstation.ServiceModel.Ua.Channels.BinaryDecoder.ReadDiagnosticInfo(String fieldName)
   at Workstation.ServiceModel.Ua.Channels.BinaryDecoder.ReadDiagnosticInfo(String fieldName)
   at Workstation.ServiceModel.Ua.Channels.BinaryDecoder.ReadDiagnosticInfoArray(String fieldName)
```

![grafik](https://user-images.githubusercontent.com/17551597/92585617-7c703a00-f295-11ea-97bd-474ea9d7bbe9.png)

**Comment by quinmars** [comment]
The `Decode` and `Encode` methods are not optional. You have to implement them correctly. That means you have to read/write the value with the correct type in the correct order. Else the internal stream of the encoder/decoder will not be advanced and the encoder/decoder will resume the parsing/writing at the wrong position in the stream.

**Comment by dojo90** [comment]
This was the solution 🙂👍
