### ISSUE TITLE
Exception when connecting to a server without certificate

### ISSUE THREAD

**Issue by chhuebner** [convertersystems/opc-ua-client#246]
ClientSessionChannel.OnOpenAsync throws System.ArgumentNullException when the server has no certificate. 

at System.IO.MemoryStream..ctor(Byte[] buffer, Boolean writable)
at Org.BouncyCastle.X509.X509CertificateParser.ReadCertificate(Byte[] input) in /_/crypto/src/x509/X509CertificateParser.cs:line 92
at Workstation.ServiceModel.Ua.Channels.ClientSessionChannel.OnOpenAsync(CancellationToken token)
at Workstation.ServiceModel.Ua.Channels.CommunicationObject.OpenAsync(CancellationToken token)

**Comment by awcullen** [comment]
Thanks for fixing this issue.
